LISTE creer_liste();
int est_vide(LISTE l);
LISTE creer_mur(int L, int H, int sens);
LISTE inser_mur(LISTE l, int L, int H, int sens);
LISTE libere_mem_liste(LISTE l);
PILE creer_pile();
int est_vide_p(PILE p);
PILE creer_coup(int x, int y);
PILE inser_coup(PILE p, int x, int y);
PILE libere_mem_pile(PILE p);
PILE pile_pop(PILE p, POS *jprec);
int victoire(SLIDER S);
SLIDER init_slider();
int control_liste(LISTE l,int L,int H);
LISTE changer_mur(LISTE,int L,int H);
LISTE changer_sens(LISTE l,int L,int H);
int cpt_liste(LISTE l);