void affichage_grille(SLIDER S);
void affichage_joueur(SLIDER S);
void masque_joueur(SLIDER S);
void affichage_sortie(SLIDER S);
void masque_sortie(SLIDER S);
void calcul_murs(SLIDER S, POINT *a, POINT *b);
void affichage_mur(SLIDER S);
void affichage(SLIDER S);
int collision_bords(SLIDER S, POINT a);
int collision_mur_vrt_g(SLIDER S, POINT *a);
int collision_mur_vrt_d(SLIDER S, POINT *a);
int collision_mur_hrz_h(SLIDER S, POINT *a);
int collision_mur_hrz_b(SLIDER S, POINT *a);
int collision_mur(SLIDER S, POINT *a, int dir);
SLIDER deplacements_perso(SLIDER S, int dir);
SLIDER undo(SLIDER S, char touche);
void jouer(SLIDER S);
void carton_joueur();
void carton_sortie();
void carton_mur();
void carton_instruction();
void carton_debut();
void partie(SLIDER S);