ploum:	plim.o plam.o ploum.o
		gcc -o ploum plim.o plam.o ploum.o
		
plim.o:	plim.c
		gcc -o plim.o -c plim.c -Wall
		
plam.o: plam.c
		gcc -o plam.o -c plam.c -Wall
		
ploum.o: ploum.c
		gcc -o ploum.o -c ploum.c -Wall